from typing import TYPE_CHECKING, Any

from components.runtime.message_runtime.protocol import (
    ComponentOccurrenceDeclaration,
    ComponentOccurrenceRegistration,
    JsonObject,
    JsonValue,
    MessageRuntime,
    RuntimeActionUnknown,
    RuntimeAddress,
    RuntimeAddressUnknown,
    RuntimeCausalTrace,
    RuntimeCuratedOperationDeclaration,
    RuntimeDeliveryStatus,
    RuntimeDeliveryUnknown,
    RuntimeError,
    RuntimeExternalBoundaryDisposition,
    RuntimeExternalBoundaryMode,
    RuntimeFailStopped,
    RuntimeHealth,
    RuntimeHistoryPage,
    RuntimeHistoryQuery,
    RuntimeLaneDeclaration,
    RuntimeLedgerFact,
    RuntimeLedgerUnavailable,
    RuntimeMessageConflict,
    RuntimeMessageEnvelope,
    RuntimeMessageKind,
    RuntimeMessageOutcome,
    RuntimeMessageReceipt,
    RuntimePayload,
    RuntimeQueueFull,
    RuntimeReconstructionReport,
    RuntimeReconstructionRequest,
    RuntimeRegistrationInvalid,
    RuntimeReplayIncompatible,
    RuntimeReplayMode,
    RuntimeReplayTargetNotPrepared,
    RuntimeRequestIndeterminate,
    RuntimeRequestOutcome,
    RuntimeRequestTimedOut,
    RuntimeSchemaUnsupported,
    RuntimeStorageVersionUnsupported,
    RuntimeTopologyConfirmation,
    RuntimeTopologyManifest,
    RuntimeTraceDisposition,
    RuntimeTraceSummary,
    RuntimeTraceSummaryPage,
)

if TYPE_CHECKING:
    from components.runtime.message_runtime.native import SqliteMessageRuntime


def __getattr__(name: str) -> Any:
    if name == "SqliteMessageRuntime":
        from components.runtime.message_runtime.native import SqliteMessageRuntime

        return SqliteMessageRuntime
    raise AttributeError(name)


__all__ = [
    "ComponentOccurrenceDeclaration",
    "ComponentOccurrenceRegistration",
    "JsonObject",
    "JsonValue",
    "MessageRuntime",
    "RuntimeActionUnknown",
    "RuntimeAddress",
    "RuntimeAddressUnknown",
    "RuntimeCausalTrace",
    "RuntimeCuratedOperationDeclaration",
    "RuntimeDeliveryStatus",
    "RuntimeDeliveryUnknown",
    "RuntimeError",
    "RuntimeExternalBoundaryDisposition",
    "RuntimeExternalBoundaryMode",
    "RuntimeFailStopped",
    "RuntimeHistoryPage",
    "RuntimeHistoryQuery",
    "RuntimeHealth",
    "RuntimeLedgerFact",
    "RuntimeLedgerUnavailable",
    "RuntimeLaneDeclaration",
    "RuntimeMessageConflict",
    "RuntimeMessageEnvelope",
    "RuntimeMessageKind",
    "RuntimeMessageOutcome",
    "RuntimeMessageReceipt",
    "RuntimePayload",
    "RuntimeQueueFull",
    "RuntimeReconstructionReport",
    "RuntimeReconstructionRequest",
    "RuntimeRegistrationInvalid",
    "RuntimeReplayIncompatible",
    "RuntimeReplayTargetNotPrepared",
    "RuntimeReplayMode",
    "RuntimeRequestOutcome",
    "RuntimeRequestIndeterminate",
    "RuntimeRequestTimedOut",
    "RuntimeSchemaUnsupported",
    "RuntimeStorageVersionUnsupported",
    "RuntimeTraceDisposition",
    "RuntimeTraceSummary",
    "RuntimeTraceSummaryPage",
    "RuntimeTopologyConfirmation",
    "RuntimeTopologyManifest",
    "SqliteMessageRuntime",
]
