"""Standard message-native adapter implementation."""

from components.runtime.component_adapter.native import (
    ActionBinding,
    ActionHandler,
    ComponentAdapter,
    ComponentEndpoint,
    ComponentExecution,
    ReplayEffectApplier,
    ReplayEffectBuilder,
    ReplayStateBinding,
    RequestDecoder,
    ResultEncoder,
    RuntimeBindingDescription,
    RuntimeBindingInvalid,
    RuntimeComponentDeadlineExceeded,
    RuntimePayloadInvalid,
    RuntimeRemoteFault,
    RuntimeReplayStateStatus,
    RuntimeTerminalEncodingFailed,
    encode_json,
)

__all__ = [
    "ActionBinding",
    "ActionHandler",
    "ComponentAdapter",
    "ComponentEndpoint",
    "ComponentExecution",
    "ReplayEffectApplier",
    "ReplayEffectBuilder",
    "ReplayStateBinding",
    "RequestDecoder",
    "ResultEncoder",
    "RuntimeBindingDescription",
    "RuntimeBindingInvalid",
    "RuntimeComponentDeadlineExceeded",
    "RuntimePayloadInvalid",
    "RuntimeRemoteFault",
    "RuntimeReplayStateStatus",
    "RuntimeTerminalEncodingFailed",
    "encode_json",
]
